---
title: "Reversion del TP"
author: "Ro Canteros"
date: "2024-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# ---Librerias---
library(readr)
library(tidyverse)
library(ggplot2)
library(ResourceSelection)

# ---Datos---
data_original <- read_delim("secondary_data.csv", 
                            delim = ";", escape_double = FALSE, trim_ws = TRUE)

hongos <- data_original %>% 
  select(class, `cap-diameter`, `cap-shape`, `gill-attachment`, `gill-color`, 
         `stem-height`, `stem-width`, `stem-color`, season) %>% 
  mutate(class = ifelse(class == "e", 1, 0)) %>% 
  replace_na(list(`gill-attachment` = "u"))

colnames(hongos) = c("class", "cap_diameter","cap_shape", "gill_attachment", 
                     "gill_color", "stem_height", "stem_width", "stem_color", 
                     "season")

hongos = hongos %>% mutate(cap_shape = as.factor(cap_shape), 
                 gill_attachment = as.factor(gill_attachment),
                 gill_color = as.factor(gill_color),
                 stem_color = as.factor(stem_color),
                 season = as.factor(season))

## Recategorizacion

hongos = hongos %>% 
  mutate(gill_color = case_when(
    gill_color == "e" | gill_color == "y" | gill_color == "o" | gill_color == "p" ~ "Calidos",
    gill_color == "u" | gill_color == "r" | gill_color == "l" ~ "Frios",
    gill_color == "w" | gill_color == "g" | gill_color == "b" ~ "Claros",
    gill_color == "n" | gill_color == "k" ~ "Oscuros",
    gill_color == "f" ~ "Ninguno"),
    gill_attachment = case_when(
      gill_attachment == "a" | gill_attachment == "x"~ "Adjuntas",
      gill_attachment == "s" | gill_attachment == "p" | gill_attachment == "u" ~ "Otros",
      gill_attachment == "e"  ~ "Libre",
      gill_attachment == "f" ~ "Ninguno",
      gill_attachment == "d"~ "Decurrente"),
    stem_color = gill_color,
    cap_shape = case_when(
      cap_shape == "f" ~ "Chato",
      cap_shape == "s" ~ "Hundido",
      cap_shape == "b" | cap_shape == "c" | cap_shape == "x" | cap_shape == "p" ~ "Redondeado",
      cap_shape == "o" ~ "Otros"
    ))

```

```{r}
# Extracción de la muestra
set.seed(154)
muestra <- hongos[sample(61069,250),]
```

```{r}
# Análisis descriptivo
theme_set(theme_bw())

ggplot(muestra) + 
  aes(x = factor(class), fill = factor(class)) + 
  geom_bar() +
  scale_fill_manual(values = c("slateblue", "orangered"), guide = "none") +
  scale_x_discrete(name = "Hongo", labels = c("Venenoso", "Comestible")) +
  scale_y_continuous(breaks = seq(0, 150, 25)) +
  labs(y = "Frecuencia", title = "Gráfico 1: Cantidad de hongos según categoría") 

muestra %>% 
  #saco la observacion de 60 para que se vea bien los boxplots
  filter(cap_diameter<50) %>% 
ggplot() +
  aes(y = cap_diameter, x = factor(class), color = factor(class)) +
  geom_boxplot() + 
  scale_x_discrete(name = "Hongo", labels = c("Venenoso", "Comestible")) + 
  scale_y_continuous(name = "Diámetro") +
  scale_color_manual(values = c("slateblue", "orangered"), guide = "none") +
  labs(title = "Gráfico 2: Diámetro del sombrero según tipo de hongo")

muestra %>% ggplot() +
  aes(y = stem_height, x = factor(class), color = factor(class)) +
  geom_boxplot() + 
  scale_x_discrete(name = "Hongo", labels = c("Venenoso", "Comestible")) + 
  scale_y_continuous(name = "Altura") +
  scale_color_manual(values = c("slateblue", "orangered"), guide = "none") +
  labs(title = "Gráfico 2: Altura del tallo según tipo de hongo")

muestra %>% ggplot() +
  aes(y = stem_width, x = factor(class), color = factor(class)) +
  geom_boxplot() + 
  scale_x_discrete(name = "Hongo", labels = c("Venenoso", "Comestible")) + 
  scale_y_continuous(name = "Ancho") +
  scale_color_manual(values = c("slateblue", "orangered"), guide = "none") +
  labs(title = "Gráfico 2: Ancho del tallo según tipo de hongo")

# Barras apiladas

muestra %>% group_by(cap_shape, class) %>% count() %>% 
  ggplot() +
  aes(x = cap_shape, fill = factor(class), y = n) +
  geom_bar(position = "fill",  stat="identity") +
  scale_fill_manual(values = c("slateblue", "orangered"), guide = "none") +
  scale_x_discrete(name = "Sombrero", labels = c("b" = "campana", "c" = "cónico", "f" = "plano","x" = "convexo","s" = "hundido","o" = "otros", "p" = "esferico")) +
  labs(y = "Frecuencia", 
       title = "Gráfico 2: Cantidad de hongos según la forma del sombrero") 

muestra %>% group_by(gill_attachment, class) %>% count() %>% 
  ggplot() +
  aes(x = gill_attachment, fill = factor(class), y = n) +
  geom_bar(position = "fill",  stat="identity") +
  scale_fill_manual(values = c("slateblue", "orangered"), guide = "none") +
  scale_x_discrete(name = "Láminas") +
  labs(y = "Frecuencia relativa", 
       title = "Gráfico 3: Cantidad de hongos según tipo de lámina") 

muestra %>% group_by(gill_color, class) %>% count() %>% 
  ggplot() +
  aes(x = gill_color, fill = factor(class), y = n) +
  geom_bar(position = "fill",  stat="identity") +
  scale_fill_manual(values = c("slateblue", "orangered"), guide = "none") +
  scale_x_discrete(name = "Colores") +
  labs(y = "Frecuencia relativa", 
       title = "Gráfico 4: Cantidad de hongos según color de las láminas") 

muestra %>% group_by(stem_color, class) %>% count() %>% 
  ggplot() +
  aes(x = stem_color, fill = factor(class), y = n) +
  geom_bar(position = "fill",  stat="identity") +
  scale_fill_manual(values = c("slateblue", "orangered"), guide = "none") +
  scale_x_discrete(name = "Colores") +
  labs(y = "Frecuencia relativa", 
       title = "Gráfico 4: Cantidad de hongos según color del tallo") 

muestra %>% group_by(season, class) %>% count() %>% 
  ggplot() +
  aes(x = gill_color, fill = factor(class), y = n) +
  geom_bar(position = "fill",  stat="identity") +
  scale_fill_manual(values = c("slateblue", "orangered"), guide = "none") +
  scale_x_discrete(name = "Colores") +
  labs(y = "Frecuencia relativa", 
       title = "Gráfico 4: Cantidad de hongos según color de las láminas") 


```


```{r}
# Seleccion de modelo
set.seed(245)


# ¿Cuáles variable son significativas?
mod_int <- glm(class ~ 1, family = binomial(link = "logit"), 
                     data = muestra)
mod_diam <- glm(class ~ cap_diameter, family = binomial(link = "logit"),
                data = muestra)
mod_shape <- glm(class ~ cap_shape, family = binomial(link = "logit"),
                data = muestra)
mod_gattch <- glm(class ~ gill_attachment, family = binomial(link = "logit"),
                data = muestra)
mod_gcolor <- glm(class ~ gill_color, family = binomial(link = "logit"),
                data = muestra)
mod_sheight <- glm(class ~ stem_height, family = binomial(link = "logit"),
                data = muestra)
mod_swidth <- glm(class ~ stem_width, family = binomial(link = "logit"),
                data = muestra)
mod_scolor <- glm(class ~ stem_color, family = binomial(link = "logit"),
                data = muestra)
mod_season <- glm(class ~ season, family = binomial(link = "logit"),
                data = muestra)

# Nivel de significacion =  0.1

anova(mod_int, mod_diam, test = "LRT")  # Significativa
anova(mod_int, mod_shape, test = "LRT") # Significativa
anova(mod_int, mod_gattch, test = "LRT") 
anova(mod_int, mod_gcolor, test = "LRT") 
anova(mod_int, mod_sheight, test = "LRT") 
anova(mod_int, mod_swidth, test = "LRT") 
anova(mod_int, mod_scolor, test = "LRT") 
anova(mod_int, mod_season, test = "LRT") # Significativa

```


```{r}
mod_1 <- glm(class ~ cap_diameter + cap_shape + season, family = binomial(link = "logit"),
             data = muestra)

mod_sin_diam <- glm(class ~  cap_shape + season, family = binomial(link = "logit"),
             data = muestra)

mod_sin_shape <- glm(class ~ cap_diameter + season, family = binomial(link = "logit"),
             data = muestra)

mod_sin_season <- glm(class ~ cap_diameter + cap_shape, family = binomial(link = "logit"),
             data = muestra)

# Nivel de significacion = 0.05

anova(mod_sin_diam, mod_1, test = "LRT")
anova(mod_sin_shape, mod_1, test = "LRT")
anova(mod_sin_season, mod_1, test = "LRT") # p-v = 0.09, el beta asoc. a season es 0
```


```{r}
mod_2 <- mod_sin_season

mod_3 <- glm(class ~ cap_diameter + cap_shape + gill_attachment, 
             family = binomial(link = "logit"), data = muestra)

mod_4 <- glm(class ~ cap_diameter + cap_shape + gill_color, 
             family = binomial(link = "logit"), data = muestra)

mod_5 <- glm(class ~ cap_diameter + cap_shape + stem_height, 
             family = binomial(link = "logit"), data = muestra)

mod_6 <- glm(class ~ cap_diameter + cap_shape + stem_width, 
             family = binomial(link = "logit"), data = muestra)

mod_7 <- glm(class ~ cap_diameter + cap_shape + stem_color, 
             family = binomial(link = "logit"), data = muestra)


# Nivel de significacion = 0.05

anova(mod_2, mod_3, test = "LRT") 
anova(mod_2, mod_4, test = "LRT")
anova(mod_2, mod_5, test = "LRT")
anova(mod_2, mod_6, test = "LRT")
anova(mod_2, mod_7, test = "LRT")


# El modelo final es "cap_diameter + cap_shape" = mod_2
summary(mod_2)

mod_int <- glm(class ~ cap_diameter*cap_shape , family = binomial(link = "logit"),
               data = muestra)
summary(mod_int)
anova(mod_2, mod_int, test = "LRT")

```


```{r}
# Ajuste de diferentes enlaces

modelo_logit <- mod_int
modelo_probit <- glm(class ~ cap_diameter*cap_shape, family = binomial(link = "probit"),
                     data = muestra)
modelo_cll <- glm(class ~ cap_diameter*cap_shape, family = binomial(link = "cloglog"),
                     data = muestra)

# Bondad de ajuste de cada  modelo
# H0) "El modelo ajusta" vs H1) "El modelo no ajusta"

hoslem.test(muestra$class, fitted(modelo_logit), g = 10)
hoslem.test(muestra$class, fitted(modelo_probit), g = 10)
hoslem.test(muestra$class, fitted(modelo_cll), g = 10)

# En los 3 casos NO rechazo H0), por lo que no hay falta de bondad de ajuste en 
# ninguno de los 3 enlaces

# Criterio de Akaike:
AIC(modelo_logit, modelo_probit, modelo_cll)
# El enlace "cloglog" queda descartado por tener el AIC mayor, peeeero el debate
# está entre el logit (331.58) y el probit (331.38).
```

```{r}
# Dada la duda entre "logit" y "probit", evaluo si el enlace es adecuado:

pred.logit<-predict(modelo_logit)
muestra$pred.2.logit<-pred.logit*pred.logit

modelo_logit.2 <- glm(class ~ cap_diameter*cap_shape + pred.2.logit, 
                        family=binomial(link="logit"),
                        data=muestra)
anova(modelo_logit, modelo_logit.2, test="LRT")

pred.probit<-predict(modelo_probit)
muestra$pred.2.probit<-pred.probit*pred.probit

modelo_probit.2 <- glm(class ~ cap_diameter*cap_shape + pred.2.probit, 
                        family=binomial(link="probit"), 
                        data=muestra)
anova(modelo_probit, modelo_probit.2, test="LRT")

pred.cll<-predict(modelo_cll)
muestra$pred.2.cll<-pred.cll*pred.cll

modelo_cll.2 <- glm(class ~ cap_diameter*cap_shape + pred.2.cll, 
                        family=binomial(link="cloglog"), 
                        data=muestra)
anova(modelo_cll, modelo_cll.2, test="LRT")
```

